/** ISO 3166-1 alpha-2 → deutscher Anzeigename (Overrides für Kurzformen). */
export const COUNTRY_NAMES: Record<string, string> = {
  AE: "Vereinigte Arabische Emirate",
  AF: "Afghanistan",
  AL: "Albanien",
  AM: "Armenien",
  AO: "Angola",
  AR: "Argentinien",
  AT: "Österreich",
  AU: "Australien",
  AZ: "Aserbaidschan",
  BA: "Bosnien und Herzegowina",
  BB: "Barbados",
  BE: "Belgien",
  BG: "Bulgarien",
  BH: "Bahrain",
  BO: "Bolivien",
  BR: "Brasilien",
  BS: "Bahamas",
  BT: "Bhutan",
  BW: "Botswana",
  BY: "Belarus",
  CA: "Kanada",
  CH: "Schweiz",
  CI: "Elfenbeinküste",
  CL: "Chile",
  CM: "Kamerun",
  CN: "China",
  CO: "Kolumbien",
  CR: "Costa Rica",
  CY: "Zypern",
  CZ: "Tschechien",
  DE: "Deutschland",
  DK: "Dänemark",
  DO: "Dominikanische Republik",
  DZ: "Algerien",
  EC: "Ecuador",
  EE: "Estland",
  EG: "Ägypten",
  ES: "Spanien",
  ET: "Äthiopien",
  FI: "Finnland",
  FJ: "Fidschi",
  FR: "Frankreich",
  GB: "Vereinigtes Königreich",
  GE: "Georgien",
  GH: "Ghana",
  GR: "Griechenland",
  GT: "Guatemala",
  GW: "Guinea-Bissau",
  HN: "Honduras",
  HK: "Hongkong",
  HR: "Kroatien",
  HT: "Haiti",
  HU: "Ungarn",
  ID: "Indonesien",
  IE: "Irland",
  IL: "Israel",
  IN: "Indien",
  IQ: "Irak",
  IR: "Iran",
  IS: "Island",
  IT: "Italien",
  JM: "Jamaika",
  JO: "Jordanien",
  JP: "Japan",
  KE: "Kenia",
  KG: "Kirgisistan",
  KH: "Kambodscha",
  KR: "Südkorea",
  KW: "Kuwait",
  KZ: "Kasachstan",
  LA: "Laos",
  LB: "Libanon",
  LC: "St. Lucia",
  LK: "Sri Lanka",
  LT: "Litauen",
  LU: "Luxemburg",
  LV: "Lettland",
  MA: "Marokko",
  MC: "Monaco",
  MD: "Moldawien",
  ME: "Montenegro",
  MG: "Madagaskar",
  MK: "Nordmazedonien",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolei",
  MO: "Macao",
  MR: "Mauretanien",
  MT: "Malta",
  MU: "Mauritius",
  MW: "Malawi",
  MX: "Mexiko",
  MY: "Malaysia",
  MZ: "Mosambik",
  NA: "Namibia",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Niederlande",
  NO: "Norwegen",
  NP: "Nepal",
  NR: "Nauru",
  NZ: "Neuseeland",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PG: "Papua-Neuguinea",
  PH: "Philippinen",
  PK: "Pakistan",
  PL: "Polen",
  PR: "Puerto Rico",
  PT: "Portugal",
  PY: "Paraguay",
  QA: "Katar",
  RO: "Rumänien",
  RS: "Serbien",
  RU: "Russland",
  RW: "Ruanda",
  SA: "Saudi-Arabien",
  SB: "Salomonen",
  SC: "Seychellen",
  SE: "Schweden",
  SG: "Singapur",
  SI: "Slowenien",
  SK: "Slowakei",
  SL: "Sierra Leone",
  SV: "El Salvador",
  SY: "Syrien",
  TH: "Thailand",
  TL: "Osttimor",
  TN: "Tunesien",
  TO: "Tonga",
  TR: "Türkei",
  TT: "Trinidad und Tobago",
  TW: "Taiwan",
  TZ: "Tansania",
  UA: "Ukraine",
  UG: "Uganda",
  US: "USA",
  UY: "Uruguay",
  UZ: "Usbekistan",
  VE: "Venezuela",
  VN: "Vietnam",
  VU: "Vanuatu",
  ZA: "Südafrika",
  ZM: "Sambia",
  ZW: "Simbabwe",
};

let germanRegionNames: Intl.DisplayNames | undefined;

function getGermanRegionNames(): Intl.DisplayNames {
  if (!germanRegionNames) {
    germanRegionNames = new Intl.DisplayNames(["de"], { type: "region" });
  }
  return germanRegionNames;
}

export function getCountryName(
  code: string,
  worldNames?: Record<string, string>
): string {
  const cc = code.toUpperCase();
  if (COUNTRY_NAMES[cc]) return COUNTRY_NAMES[cc];
  if (worldNames?.[cc]) return worldNames[cc];

  const localized = getGermanRegionNames().of(cc);
  if (localized && localized !== cc) return localized;

  return cc;
}
